### ISSUE TITLE
Force requirements

### ISSUE THREAD

**Issue by heutger** [lamw/ghettoVCB#105]
Hi,

I'm wondering, why ghettoVCB could not be updated like http://rene.margar.fr/2012/05/client-nut-pour-esxi-5-0/ updated it's upsmon client, which result in being able to stay on the system with Community Mode and does not require force switch to install. As the paths used for the conf as well as the script (still being overwritten each reboot, so I was required to store the script and conf on my datastore volume, as the script on the Github download still has some bugs on 6.5 mentioned in the issues tracker) seems to be protected (and useless as stated in the brackets before), I would prefer a version, which does not violate policy and can be installed without force. Any comments?

Regards,
Christian

**Comment by lamw** [comment]
Thanks for the comment.

A couple of things I want to quickly point out:

1) This is a completely **free** solution, there are and will be limitations. The "force" requirement is an expected behavior for any "Community" created VIBs which ghettoVCB is. For official partner based solutions, partners can sign a VIB which would not require the --force flag. If this is something that is unacceptable, than you are more than welcome to look at other paid solutions which don't have such limitations. 

2) In terms of the VIB overriding the existing script, again, this is an expected behavior of "updating" a VIB. I'm not sure how else would you get the latest script then if it doesn't replace the existing file? If behavior is not acceptable, you always have the option of manually managing the script. Most users store the actual configuration file else where which they can centrally manage and the only thing they update is the VIB for new versions. As mentioned earlier, this is a community solution which is completely open sourced. You can even build your own VIB (instructions have been fully documented) as you see please if you don't like the current implementation.

**Comment by heutger** [comment]
Hi,

first thanks for your effort to create ghettoVCB. However, I would also be happy to pay for such a solution, if it's an affordable one time fee (as I use it only for private use). I didn't found any other solutions, payable or not, which work such well with free ESXi as again, it's for private use, so the payed license is too expensive for just running one VM, moving from a Mac Mini Server with Fusion (all licensed) to a NUC with ESXi.

I tried to fix the shell script as of the 6.5 bug on mounting NFS volumes, however, this fix get overwritten each time I reboot my ESXi. Same for the conf, I tried to do my settings inside the configuration file at the path, where the conf file is written (thought, that /etc is for settings), but same behaviour, each reboot the settings are gone.

So what I just ask, the Nutclient/upsmon author was able to update his script with no need of the force flag. Maybe I didn't explain my usage correctly, as I have set ESXi to community level, so it's not about the signature but about writing in paths, which are violating the policies of VMware, e.g. preventing me from updating (without force flag again or by removing ghettoVCB for updating).

Thanks again for your script!

**Comment by lamw** [comment]
Apologies, but its still not clear on what you're asking for ... Looking at the Nutclient/upsmon installer script, its simply ignoring the sig check (hence not needing -f flag). Is the ask to be able to install the script via the VIB and be able to apply future updates w/o overriding existing changes? If so, that won't be possible as mentioned earlier. If not, could you provide an example which might help

**Comment by heutger** [comment]
Hi, yes, that was my intention. Sad to hear, that’s not possible. However, I left my NUC installation and switched to the cloud, so no need any more.

**Comment by lamw** [comment]
I did some more digging yesterday and I believe there might be a solution for this, specifically if you're using the templates or configuration file (e.g. /etc/ghettovcb/ghettovcb.conf). If you use do "esxcli software vib install", it'll override all files as expected but if you do "esxcli software vib update" then it'll preserve files that have since changed. The latter should allow users to get a new version of ghettoVCB and preserve the existing configuration file on the host (which I've been doing some testing). This does require a new build of the VIB as I noticed the config files are current in read-only mode and hence changes wouldn't persist.
