### ISSUE TITLE
VM name containing parenthesis 

### ISSUE THREAD

**Issue by gnieark** [lamw/ghettoVCB#150]
Hello.

VM name containing parenthesis are not backuped
"failed to locate and extract VM_ID for ..."

ghettoVCB.sh -m VM(parenthesis)
fails
ghettoVCB.sh -m VM\(parenthesis\)
fails
ghettoVCB.sh -a
fails if one VM got parenthesis.
ghettoVCB.sh -m "VM(parenthesis")
fails

I renamed the VM without parenthesis, It works.

thx for your work on ghetto!

**Comment by ffejtable** [comment]
For the -m switch, you would have to put the parameter in a single quote so the shell does not interpret the parenthesis.  ie `ghetoVCB.sh -m 'VM(parenthesis' ` This is a shell issue, and not really a ghettoVCB issue.  However even if you did put it in single quotes, it would fail as it would then run into a ghettoVCB limitation, as you see with the -a switch.  It's the same issue I have for using square brackets [] in my VM names.  I just put together a fix for the square brackets that I think would work for parenthesis as well with a very small modification. If I can figure out how to post it here I'll do that...

**Comment by gnieark** [comment]
Thx very much!

**Comment by ffejtable** [comment]
Sorry, got sidetracked with this a little bit, as I have been in the process of converting the shell script to Python 3.5 (ESX 6.5+).

Are you still interested in the fixes to allow parenthesis in the current code?  I have not yet fully tested the changes I have made for the square brackets []. I performed the backups I needed and was satisfied for now until I run into another issue with I can fix on my own easily enough.  Some functionality/features may still be broken.  In particular I have not attempted to perform a restore, which at the very least I should attempt.  This is a separate script that I need to modify, which I have not even looked at yet.

Things I need to do...

Clean up the changes I have made to include only what is necessary as I have some debugging output/comments in there that need to be removed.

Put together a list of all the various use cases (command line options) and test with each of those.

Make sure restore works (which will likely require changes to the restore script)

From what I gather the various proposed/published fixes for other various issues have not all been merged, either, so if you incorporated any of those, they may not be included in my update. 

I'll need a few days to update this at least depending on how much my day job gets in the way ;)

**Comment by ffejtable** [comment]
I submitted my changes and did a pull request.  I don't know how often these are checked and approved, and then I think they have to be merged.  While I have submitted fixes in the past for other projects, this is the first time I did it the "right" way via a pull request.  

I believe you can download the updated script by clicking on the number next to Fork near the top right part of the page.  Then click on the ghettoVCB part next to my name "ffejtable".  Finally in the "Branch" dropdown box select patch-1 and you should then see that ghettoVCB.sh was updated recently.  I actually made 2 changes, since the master that I forked from did not have the conditional fix (I think it was #145) applied.

I haven't tested these changes under all possible conditions, so if you find any options that it doesn't work with, let me me.

The Restore script is actually interesting.  Brackets and Parenthesis already work without changes.  It's actually VMs containing spaces that are not registering correctly, and I have tried to do so both via the CLI using vim-cmd solo/registervm and through the WebUI (6.5).  I'll see if a defect has been filed here for that, although this isn't really specific to ghettoVCB.

**Comment by ffejtable** [comment]
Turns out the spaces issue is a problem with the restore script which is no placing the VM Display name in quotes in the .vmx file.. This has already been reported and fixed, issue #143 

"ghettoVCB-resotre.sh / missing double quote for displayName in vmx file"
