### ISSUE TITLE
email notification not working?

### ISSUE THREAD

**Issue by SebastianSchultz** [lamw/ghettoVCB#172]
Hello,

I'm new to ESXi and ghettoVCB but I have got it working so far :)
But the email notification is not working.
I'm wondering why because I really set the correct paramters in the script.
The mailserver is hosted by my ISP.
I created a new mailbox and entered all data in the script.

In the log nothing appears. No email successful sent message or any error message regarding the mail sending.

Do you have any idea?

**Comment by SebastianSchultz** [comment]
Hello,

does no one has an idea?

When I send mail with netcat from console:

`
Command: nc <MY_MAILSERVER_AT_ISP> 25
220 <MY_MAILSERVER_AT_ISP> ESMTP
EHLO <MY_ESXI_HOST>
250-<MY_MAILSERVER_AT_ISP>
250-PIPELINING
250-SIZE 102400000
250-VRFY
250-ETRN
250-STARTTLS
250-AUTH PLAIN LOGIN
250-AUTH=PLAIN LOGIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN
AUTH LOGIN
334 <BASE64_RETURN_OF_MAILSERVER>
<USERNAME AS BASE64>
334 <BASE64_RETURN_OF_MAILSERVER>
<PASSWORD AS BASE64>
235 2.7.0 Authentication successful
MAIL FROM:<SENDER_ADDRESS>
250 2.1.0 Ok
RCPT TO:<RECIPIENT_ADDRESS>
250 2.1.5 Ok
DATA
354 End data with <CR><LF>.<CR><LF>
This is a test.
.
250 2.0.0 Ok: queued as E1D3E4B41D2C
QUIT
221 2.0.0 Bye
`

Then everything works fine and the email is in my inbox.

What I'm doing wring?

**Comment by vampire337** [comment]
I ultimately found that ISP SMTP is garbage for debugging purposes, aside from the possibility that they might be causing some of your problems. I recommend switching to a service like smtp2go.com for outbound SMTP, because it's free for low end use and you can verify that your emails actually got to the SMTP from your server.

That said, you should post your email configuration settings in order for anyone to be of much help. Here are the settings which are working for me on ESXi 6.7U2. If they don't work for you, post up what you're using and maybe someone offer advice.

EMAIL_ALERT=1
EMAIL_LOG=1
EMAIL_SERVER=[your smtp server address here]
EMAIL_SERVER_PORT=25
EMAIL_DELAY_INTERVAL=1
EMAIL_TO=support@yourdomain.com
EMAIL_ERRORS_TO=support@yourdomain.com
EMAIL_FROM=noreply-vhost@yourdomain.com
