### ISSUE TITLE
cannot upgrade with the vib installed

### ISSUE THREAD

**Issue by dspolleke** [lamw/ghettoVCB#63]
Installer will HALT with error:

THis program has encountered an error: 
Error (see log for more info):

Could not obtain module order from existing db 
the isntallation profile could not be validated due to the following errors
VIB virtuallyGhetto_bootbank_ghettoVCB_1.0.0-0.0.0 violates extensibility rule checks [u (line 24: col 0_ Element vib failed to validate content]
##  VIB vrituallyGhetto_bootbank_ghettoVCB_1.0.0-0.0.0  acceptance level is community which is not compliant with the ImageProfile acceptance level partner

after reboot uninstalled the vib.. 

update went through nicely

**Comment by creativeview** [comment]
I've had the same issue:  **VIB virtuallyGhetto_bootbank_ghettoVCB_1.0.0-0.0.0's acceptance level is community, which is not compliant with the ImageProfile acceptance level partner
 To change the host acceptance level, use the 'esxcli software acceptance set' command.**

I tried to change the acceptance level using 

`esxcli software acceptance set --level=CommunitySupported`

** [AcceptanceConfigError]
 Unable to set acceptance level of community due to installed VIBs virtuallyGhetto_bootbank_ghettoVCB_1.0.0-0.0.0 having a lower acceptance level.**

**Comment by zoic21** [comment]
Hi,

You can change acceptance level by remove ghetto vib : 
`esxcli software vib remove -n ghettoVCB`

Change acceptance : 
`esxcli software acceptance set --level=CommunitySupported`

And readd vib : 
`esxcli software vib install -v https://github.com/lamw/ghettoVCB/raw/master/vghetto-ghettoVCB.vib -f`

But even after that I get this error : 

```
 [DependencyError]
 VIB virtuallyGhetto_bootbank_ghettoVCB_1.0.0-0.0.0 violates extensibility rule checks: [u'(line 24: col 0) Element vib failed to validate content']
 Please refer to the log file for more details.
```

**Comment by pkolmann** [comment]
I just had the same issue and was able to override it with:

~ # esxcli software profile update -d https://hostupdate.vmware.com/software/VUM/PRODUCTION/main/vmw-depot-index.xml -p ESXi-5.5.0-20160904001-standard **-f**

**Comment by CollinChaffin** [comment]
Is there any traction on a fix for this?  This VIB literally breaks a ESX6.0 installer.  The image will fail, and the warning above "VIB virtuallyGhetto_bootbank_ghettoVCB_1.0.0-0.0.0 violates extensibility" is thrown when using customizer to even add this VIB to the ISO installer.  It was always really nice to be able to include this VIB directly in my installers, but this issue is really causing a lot of headaches so hopefully someone can come up with a code fix to again allow it to be integrated into the initial installer and not have to use the above posted workaround to force the install after the host is already built.

**Comment by jjrbg** [comment]
This is an issue stopping me upgrading ESXi...
esxcli software vib remove --vibname=ghettoVCB --force
 [ValueError]
 Invalid acceptance level value ''
 Please refer to the log file for more details.

**Comment by enoch85** [comment]
Any update on this? It's really annoying tbh.

**Comment by jesseborden** [comment]
I found a solution to use just the script, with some modification for ESXi 6.5. I had to reinstall ESXi, due to having the same problem as everyone else here, but it might help to never use the VIB again.

(1.) Modify the ghettoVCB script... 

****************************
Remove this.... (lines 280-290)
    if [[ -f /usr/bin/vmware-vim-cmd ]]; then

        VMWARE_CMD=/usr/bin/vmware-vim-cmd

        VMKFSTOOLS_CMD=/usr/sbin/vmkfstools

    elif [[ -f /bin/vim-cmd ]]; then

        VMWARE_CMD=/bin/vim-cmd

        VMKFSTOOLS_CMD=/sbin/vmkfstools

    else

        logger "info" "ERROR: Unable to locate *vimsh*! You're not running ESX(i) 3.5+, 4.x+, 5.x+ or 6.x!"

        echo "ERROR: Unable to locate *vimsh*! You're not running ESX(i) 3.5+, 4.x+, 5.x+ or 6.x!"

        exit 1

    fi
**************************************
Add this...
VMWARE_CMD=/bin/vim-cmd
    VMKFSTOOLS_CMD=/sbin/vmkfstools
**************************************
Change this.....
VM_BACKUP_VOLUME=/vmfs/volumes/mini-local-datastore-hdd/backups

to this (or wherever you want the backups to be in the datastore)....
VM_BACKUP_VOLUME=/vmfs/volumes/datastore2/backups

**THEN SAVE THE FILE IN YOUR DATASTORE**
(3.) Edit the local.sh file to re-add the cron task following a reboot.
cd /etc/rc.local.d
vi local.sh

Add this to local.sh....

#Kill cron service
/bin/kill $(cat /var/run/crond.pid)

#Ensure scheduled task is added
/bin/echo '0   23    *   *   0,3  /vmfs/volumes/datastore2/scripts/ghettoVCB.sh -a > /dev/null'>> /var/spool/cron/crontabs/root

#Start cron service
/usr/lib/vmware/busybox/bin/busybox crond

(4.) from the SSH terminal 
cd /vmfs/volumes/datastore2/scripts/ghettoVCB.sh
chmod a+x ./ghettoVCB.sh

(5.) from the SSH terminal, test the script... 
cd /vmfs/volumes/datastore2/scripts/ghettoVCB.sh
chmod a+x ./ghettoVCB.sh
./ghettoVCB.sh

**Comment by ucola** [comment]
Same issue with ESXi 6.7U1. I want to try to upgrade it to U2 and became also this issue. Any ideas?

**Comment by ucola** [comment]
Simple solution... Uninstall the VIB, then Upgrade ESXi, after Upgrade install the VIB again

- esxcli software vib remove  --vibname=ghettoVCB

**Comment by Blinkenn** [comment]
uninstalling the VIB removes the /etc/ghettovcb/ghettoVCB.conf, so if you're ok with re-doing any custom settings, I guess that's a workaround.
